name: Generate ScalaDocs

on:
  push:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Generate Scaladoc
        run: ./gradlew scaladoc --info

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          branch: gh-pages
          build_dir: build/docs/scaladoc/